name: Test DevOps Script

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Test Bash script
        run: |
          chmod +x scripts/system-monitor.sh
          ./scripts/system-monitor.sh
      
      - name: Test Docker build
        run: |
          docker build -t system-monitor .
          docker run --rm system-monitor
